# Generated by Django 5.0.6 on 2024-07-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeltask',
            old_name='image_url',
            new_name='image_download_url',
        ),
        migrations.RenameField(
            model_name='modeltask',
            old_name='model_url',
            new_name='model_download_url',
        ),
    ]
