# Generated by Django 5.0.6 on 2024-07-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0002_rename_image_url_modeltask_image_download_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageList',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='套装_id')),
                ('caption', models.CharField(max_length=64, verbose_name='套装名称')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='套装描述')),
                ('createTime_Internal', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('alterTime_Internal', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '套装 表',
                'verbose_name_plural': '套装 表',
            },
        ),
        migrations.CreateModel(
            name='TutorialList',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='教程_id')),
                ('title', models.CharField(max_length=64, verbose_name='教程标题')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='教程描述')),
                ('componentSum', models.IntegerField(default=0, verbose_name='含有元件数')),
                ('imgFile', models.FileField(blank=True, null=True, upload_to='tutotial/', verbose_name='教程文件')),
                ('key', models.CharField(blank=True, max_length=256, null=True, verbose_name='教程key')),
                ('createTime_Internal', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('alterTime_Internal', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '教程 表',
            },
        ),
        migrations.CreateModel(
            name='ComponentList',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='元件_id')),
                ('sn', models.CharField(max_length=64, verbose_name='元件编号')),
                ('caption', models.CharField(max_length=64, verbose_name='元件名称')),
                ('btype', models.IntegerField(choices=[(0, '未定义'), (1, '条'), (2, '板'), (3, '块'), (4, '其他')], default=0, verbose_name='元件类型')),
                ('color', models.IntegerField(choices=[(0, '未定义'), (1, '条'), (2, '板'), (3, '块'), (4, '其他')], default=0, verbose_name='元件颜色')),
                ('imgFile', models.FileField(blank=True, null=True, upload_to='bricks/', verbose_name='元件img文件')),
                ('createTime_Internal', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('alterTime_Internal', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('package', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='model3d.packagelist', verbose_name='所属套装')),
            ],
            options={
                'verbose_name': '元件 表',
                'verbose_name_plural': '元件 表',
            },
        ),
    ]
