# Generated by Django 5.0.6 on 2024-07-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0003_packagelist_tutoriallist_componentlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentlist',
            options={'verbose_name': '元件表', 'verbose_name_plural': '元件表'},
        ),
        migrations.AlterModelOptions(
            name='packagelist',
            options={'verbose_name': '元件套装表', 'verbose_name_plural': '元件套装表'},
        ),
        migrations.AlterModelOptions(
            name='tutoriallist',
            options={'verbose_name': '教程表', 'verbose_name_plural': '教程表'},
        ),
    ]
