# Generated by Django 5.0.6 on 2024-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0004_alter_componentlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltask',
            options={'verbose_name': '生成任务表', 'verbose_name_plural': '生成任务表'},
        ),
        migrations.AlterModelOptions(
            name='tutoriallist',
            options={'verbose_name': '生成教程表', 'verbose_name_plural': '生成教程表'},
        ),
        migrations.RenameField(
            model_name='componentlist',
            old_name='color',
            new_name='bcolor',
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='bricks',
            field=models.CharField(max_length=255, verbose_name='选择的元件'),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='image_download_url',
            field=models.URLField(verbose_name='模型预览图保存地址'),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='lego_url',
            field=models.URLField(verbose_name='乐高方案保存地址'),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='model_download_url',
            field=models.URLField(verbose_name='模型保存地址'),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='prompt',
            field=models.TextField(verbose_name='提示词'),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='task_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='任务_id'),
        ),
        migrations.AlterField(
            model_name='tutoriallist',
            name='imgFile',
            field=models.FileField(blank=True, null=True, upload_to='tutotial/', verbose_name='教程img文件'),
        ),
    ]
