# Generated by Django 5.0.6 on 2024-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model3d', '0005_alter_modeltask_options_alter_tutoriallist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentlist',
            name='bcolor',
            field=models.IntegerField(choices=[(1, '白'), (2, '黑'), (3, '红'), (4, '绿')], default=0, verbose_name='元件颜色'),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='bricks',
            field=models.TextField(verbose_name='选择的元件'),
        ),
    ]
